### ISSUE TITLE
Add $BORK logo to Nova

### ISSUE THREAD

**Issue by dogwifdots** [novasamatech/nova-utils#2768]
WOOF Nova team,
1st
Our $WIFD main token logo update is still stuck in the Pull Request #2707:
https://github.com/novasamatech/nova-utils/pull/2707

2nd 
New token $BORK
Ticker: $BORK
Name: BORK
Asset Hub ID: 690
HydraDX ID: 1000148
Total Supply: 690

BORK logo in black-white (round):
![BORK_4](https://github.com/novasamatech/nova-utils/assets/168309605/18186780-33f0-411f-8e3d-e1ea67af3b67)

BORK logo in black-white (square):
![BORK](https://github.com/novasamatech/nova-utils/assets/168309605/de01840a-746d-46d2-b5df-affe0f8fc4b7)

Many BORK in advance for your support!
Dogwifdots dev

**Comment by dogwifdots** [comment]
@Leemo94 can you please support our pups to get their $WIFD and $BORK a nice logo? 🐶🩷

**Comment by leohar** [comment]
Thank you, added here: https://github.com/novasamatech/nova-utils/pull/2904
